//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudoShiaiWeb
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class judoshiaiEntities : DbContext
    {
        public judoshiaiEntities()
            : base("name=judoshiaiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<clubb> clubbs { get; set; }
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<judoka> judokas { get; set; }
        public virtual DbSet<competitionJudoka> competitionJudokas { get; set; }
        public virtual DbSet<vwShowJudoka> vwShowJudokas { get; set; }
        public virtual DbSet<vwAddJudoka> vwAddJudokas { get; set; }
        public virtual DbSet<belt> belts { get; set; }
        public virtual DbSet<vwListCompetition> vwListCompetitions { get; set; }
        public virtual DbSet<vwExportJ> vwExportJS { get; set; }
    }
}
