//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudoShiaiWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwAddJudoka
    {
        public int id { get; set; }
        public Nullable<int> clubbId { get; set; }
        public string clubbName { get; set; }
        public string last { get; set; }
        public string name { get; set; }
        public Nullable<int> birthyear { get; set; }
        public string beltName { get; set; }
        public string pnr { get; set; }
        public string sex { get; set; }
    }
}
