//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JudoShiaiWeb
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListCompetition
    {
        public int id { get; set; }
        public string name { get; set; }
        public string place { get; set; }
        public Nullable<int> tatamis { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> maxcompetitors { get; set; }
        public Nullable<bool> candouble { get; set; }
        public Nullable<int> numcompetitors { get; set; }
        public string clubbName { get; set; }
        public Nullable<int> competitionStatus { get; set; }
    }
}
